FORMAT: 1A
HOST: http://itdashboard-dev/api/v1

# Matsu Borough IT Dashboard API

The Dashboard is a collection of utilities used internally by the MSB IT Department.

## Server Collection [/Server]

### List All Servers [GET]

You may get a list of all the servers maintained by the IT Department.

+ Response 200 (application/json)

        {
            "total": 86,
            "per_page": 100,
            "current_page": 1,
            "last_page": 1,
            "next_page_url": null,
            "prev_page_url": null,
            "from": 1,
            "to": 86,
            "data": [
                {
                    "id": "1",
                    "name": "poseidon",
                    "description": "Hosts many of the smaller SQL databases.",
                    "cname": "neptune",
                    "ip": "192.168.1.10",
                    "inactive_flag": "0",
                    "production_flag": "1",
                    "last_windows_update": "2015-09-24",
                    "created_at": "2016-01-13 18:24:58.000",
                    "updated_at": "2016-01-13 18:24:58.000",
                    "applications": [
                        {
                            "id": "3",
                            "name": "Microsoft SQL Server",
                            "description": "Relational DB Server",
                            "inactive_flag": "0",
                            "created_at": "2016-01-13 18:24:59.000",
                            "updated_at": "2016-01-13 18:24:59.000",
                            "pivot": {
                                "server_id": "1",
                                "application_id": "3",
                                "created_at": "2016-01-13 18:24:59.000",
                                "updated_at": "2016-01-13 18:24:59.000"
                            }
                        }
                    ],
                    "databases": [
                        {
                            "id": "3",
                            "name": "Training",
                            "description": "Training Database",
                            "rpo": "15 min",
                            "rto": "1 hour",
                            "dr_strategy": "mirrored, synchronous",
                            "ha_strategy": "n/a",
                            "upgrade_readiness": "ready",
                            "inactive_flag": "0",
                            "ignore_flag": "0",
                            "production_flag": "1",
                            "server_id": "1",
                            "created_at": "2016-01-13 18:24:59.000",
                            "updated_at": "2016-01-13 18:24:59.000",
                            "pivot": {
                                "server_id": "1",
                                "database_id": "3",
                                "created_at": "2016-01-13 18:24:59.000",
                                "updated_at": "2016-01-13 18:24:59.000"
                            }
                        }
                    ]
                }
            ]
        }

### Create a New Server [POST]

You may create a new Server using this action. It takes a JSON
object containing the server attributes.

+ Request (application/json)

        {
            "name": "shareptapp",
            "description" : "Production Sharepoint Application Server",
            "cname" : "spapp",
            "ip" : "192.168.1.11",
            "inactive_flag" : 0,
            "production_flag" : 1,
            "people" : [1,3,12,17],
            "applications" : [4,10,12],
            "tags" : [1,4,10]
        }

+ Response 201 (application/json)

    + Headers

            Location: /Server/2

    + Body

            {
                "errors": false,
                "message": "Operation Completed Successfully"
            }
